[web]
# Place your provisioned EC2 instance IP address here:
nginx_server ansible_host=127.0.0.1 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/gitops-deployer-key.pem

[web:vars]
ansible_python_interpreter=/usr/bin/python3
